spring:
  application:
    name: forecast-app
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/forecast_app}
    username: ${DB_USER:forecast_app}
    password: ${DB_PASSWORD:kapsch}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      data-locations: classpath:/database/data.sql

client:
  forecast-source:
    url: https://api.open-meteo.com/v1/
    timeout: 10
    currentWeather: true

management:
  endpoint:
    health:
      show-details: always